spring:
  application:
    name: airpricing-ws
  security:
    oauth2:
      client:
        registration:
          amadeus:
            provider: amadeus
            authorization-grant-type: client_credentials
            client-id: I0O97n5o8YYGAtknZNJT5owhKAKe8dC5
            client-secret: cTFPrvVy5Tq9qgfX
        provider:
          amadeus:
            token-uri: https://test.api.amadeus.com/v1/security/oauth2/token


application:
  configuration:
    webflux-buffer-size: 16777216
  amadeus:
    base-path: https://test.api.amadeus.com/v2
    endpoint-flight-offers: /shopping/flight-offers


server:
  port: 8095


