spring:
  application:
    name: airpricing-ws
  security:
    oauth2:
      client:
        registration:
          amadeus:
            provider: amadeus
            authorization-grant-type: client_credentials
            client-id: I0O97n5o8YYGAtknZNJT5owhKAKe8dC5
            client-secret: cTFPrvVy5Tq9qgfX
        provider:
          amadeus:
            token-uri: https://test.api.amadeus.com/v1/security/oauth2/token
  mvc:
    converters:
      preferred-json: gson
  datasource:
    url: jdbc:postgresql://localhost:8001/airpricing
    username: james
    password: JHvjJ2YUiZHLo9
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: airpricing_schema

application:
  configuration:
    webflux-buffer-size: 16777216
  amadeus:
    base-path-v1: https://test.api.amadeus.com/v1
    base-path-v2: https://test.api.amadeus.com/v2
    endpoint-flight-offers: /shopping/flight-offers
    endpoint-airport: /reference-data/locations



server:
  port: 8095


