spring:
  application:
    name: airpricing-ws
  security:
    oauth2:
      client:
        registration:
          amadeus:
            provider: amadeus
            authorization-grant-type: client_credentials
            client-id: ULQPIaTKiZk7V3LD6yY0RZ0oQtXAmejm
            client-secret: KWNFHTlCGHdsdo9E
        provider:
          amadeus:
            token-uri: https://test.api.amadeus.com/v1/security/oauth2/token


application:
  configuration:
    webflux-buffer-size: 16777216
  amadeus:
    base-path: test.api.amadeus.com/v2
    endpoint-flight-offers: /shopping/flight-offers


server:
  port: 8095


