spring:
  application:
    name: airpricing-ws

api:
  amadeus:
    base-url: test.api.amadeus.com/v2
    endpoint-flight-offers: /shopping/flight-offers
    authorization-grant-type: client_credentials
    client-id: SvbnHJwcAhu5TqdKGF4DdBF007M9COZt
    client-secret: vAXMUSAxQ2DZZIq7
    token-uri: https://test.api.amadeus.com/v1/security/oauth2/token

server:
  port: 8095


